import fs from 'node:fs';
import path from 'node:path';
import { createClient } from '@supabase/supabase-js';

const cwd = process.cwd();
function readEnvFile(file) {
  const full = path.join(cwd, file);
  if (!fs.existsSync(full)) return {};
  const out = {};
  for (const raw of fs.readFileSync(full, 'utf8').split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const i = line.indexOf('=');
    if (i < 0) continue;
    const key = line.slice(0, i).trim();
    let value = line.slice(i + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
    out[key] = value;
  }
  return out;
}
const env = { ...readEnvFile('.env'), ...process.env };
const url = env.PUBLIC_SUPABASE_URL;
const key = env.PUBLIC_SUPABASE_PUBLISHABLE_KEY || env.PUBLIC_SUPABASE_ANON_KEY;
if (!url || !key) {
  console.error('Missing PUBLIC_SUPABASE_URL / PUBLIC_SUPABASE_PUBLISHABLE_KEY in .env');
  process.exit(1);
}
const supabase = createClient(url, key, { auth: { persistSession: false } });
const { data, error } = await supabase.from('seo_pages').select('*').order('path');
if (error) {
  console.error('SEO sync failed:', error.message);
  console.error('Run supabase/seo-management.sql first.');
  process.exit(1);
}
const normalize = p => {
  if (!p) return '/';
  const clean = String(p).split('?')[0].split('#')[0];
  return clean === '/' ? '/' : `/${clean.replace(/^\/+|\/+$/g, '')}/`;
};
const entries = {};
for (const row of data || []) {
  entries[normalize(row.path)] = {
    title: row.seo_title || undefined,
    description: row.meta_description || undefined,
    focusKeyword: row.focus_keyword || undefined,
    canonicalUrl: row.canonical_url || undefined,
    index: row.index_enabled !== false,
    schemaType: row.schema_type || undefined,
    ogTitle: row.og_title || undefined,
    ogDescription: row.og_description || undefined,
    ogImage: row.og_image || undefined,
  };
}
const content = `// AUTO-GENERATED by \`npm run seo:sync\`.\n// Do not edit manually; manage records from /admin > SEO Yönetimi.\nexport type SeoAdminOverride = {\n  title?: string;\n  description?: string;\n  focusKeyword?: string;\n  canonicalUrl?: string;\n  index?: boolean;\n  schemaType?: string;\n  ogTitle?: string;\n  ogDescription?: string;\n  ogImage?: string;\n};\n\nexport const seoAdminOverrides: Record<string, SeoAdminOverride> = ${JSON.stringify(entries, null, 2)};\n`;
const target = path.join(cwd, 'src/data/seoAdmin.generated.ts');
fs.writeFileSync(target, content, 'utf8');
console.log(`SEO sync complete: ${Object.keys(entries).length} page override(s) written.`);

// --- Site-wide rating (TripAdvisor) -----------------------------------------
// Same idea as seo_pages above: admin edits the number in /admin, this script
// pulls the current value into a generated file so a normal `astro build`
// doesn't need a live Supabase call per page just to render the Organization
// schema. Falls back to the last-known defaults if the table doesn't exist yet
// (e.g. supabase/site-rating.sql hasn't been run) so this never blocks a build.
const FALLBACK_RATING = { ratingValue: '4.9', reviewCount: '1141' };
let rating = FALLBACK_RATING;
const { data: ratingRows, error: ratingError } = await supabase
  .from('site_rating')
  .select('rating_value,review_count')
  .eq('id', 1)
  .maybeSingle();
if (ratingError) {
  console.warn('Site rating sync skipped (table missing? run supabase/site-rating.sql):', ratingError.message);
} else if (ratingRows) {
  rating = {
    ratingValue: String(ratingRows.rating_value ?? FALLBACK_RATING.ratingValue),
    reviewCount: String(ratingRows.review_count ?? FALLBACK_RATING.reviewCount),
  };
}
const ratingContent = `// AUTO-GENERATED by \`npm run seo:sync\`.\n// Do not edit manually; manage the value from /admin > TripAdvisor Puanı.\n// Falls back to the last-synced numbers if supabase/site-rating.sql hasn't been run yet.\nexport const siteRating = ${JSON.stringify(rating, null, 2)};\n`;
const ratingTarget = path.join(cwd, 'src/data/siteRating.generated.ts');
fs.writeFileSync(ratingTarget, ratingContent, 'utf8');
console.log(`Site rating sync complete: ${rating.ratingValue}★ / ${rating.reviewCount} reviews.`);

// Keep llms.txt (GEO) in sync with the same number so the SEO structured data
// and the GEO summary never drift apart.
const llmsPath = path.join(cwd, 'public/llms.txt');
if (fs.existsSync(llmsPath)) {
  const reviewCountFormatted = Number(rating.reviewCount).toLocaleString('en-US');
  const llmsBefore = fs.readFileSync(llmsPath, 'utf8');
  const llmsAfter = llmsBefore.replace(
    /Rated [0-9.]+\/5 from [0-9,]+ reviews on TripAdvisor\./,
    `Rated ${rating.ratingValue}/5 from ${reviewCountFormatted} reviews on TripAdvisor.`
  );
  if (llmsAfter !== llmsBefore) {
    fs.writeFileSync(llmsPath, llmsAfter, 'utf8');
    console.log('llms.txt rating line updated to match.');
  }
}
