// AUTO-GENERATED by `npm run seo:sync`.
// Do not edit manually; manage records from /admin > SEO Yönetimi.
export type SeoAdminOverride = {
  title?: string;
  description?: string;
  focusKeyword?: string;
  canonicalUrl?: string;
  index?: boolean;
  schemaType?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: string;
};

export const seoAdminOverrides: Record<string, SeoAdminOverride> = {};
