// AUTO-GENERATED by `npm run seo:sync`.
// Do not edit manually; manage the value from /admin > TripAdvisor Puanı.
// Falls back to the last-synced numbers if supabase/site-rating.sql hasn't been run yet.
export const siteRating = {
  "ratingValue": "4.9",
  "reviewCount": "1141"
};
